version: "3.8"
services:
  pathfinder:
    build:
      context: pathfinder
      args:
        UPSTREAM_VERSION: v0.21.3
    restart: unless-stopped
    environment:
      PATHFINDER_ETHEREUM_API_URL: ""
      PATHFINDER_NETWORK: mainnet
      RUST_LOG: info
      PATHFINDER_DB_DIR: /usr/share/pathfinder/data
      PATHFINDER_WEBSOCKET_ENABLED: "true"
      PATHFINDER_HTTP_RPC_ADDRESS: 0.0.0.0:6060
      PATHFINDER_WS_RPC_ADDRESS: 0.0.0.0:6061
      PATHFINDER_MONITOR_ADDRESS: 0.0.0.0:9547
    volumes:
      - pathfinder-data:/usr/share/pathfinder/data
volumes:
  pathfinder-data: {}
