version: "3.8"
services:
  pathfinder:
    build:
      context: pathfinder
      args:
        UPSTREAM_VERSION: v0.21.2
    restart: unless-stopped
    environment:
      PATHFINDER_ETHEREUM_API_URL: ""
      PATHFINDER_NETWORK: mainnet
      RUST_LOG: info
      PATHFINDER_DB_DIR: /usr/share/pathfinder/data
      PATHFINDER_WEBSOCKET_ENABLED: "true"
    volumes:
      - pathfinder-data:/usr/share/pathfinder/data
    ports:
      - "9545:9545"
volumes:
  pathfinder-data: {}
