version: "3.5"
services:
  pathfinder:
    build:
      args:
        NETWORK: sepolia-testnet
    environment:
      PATHFINDER_ETHEREUM_API_URL: ws://execution.sepolia.staker.dappnode:8546
      PATHFINDER_NETWORK: sepolia-testnet
