version: "3.5"
services:
  pathfinder:
    build:
      args:
        NETWORK: mainnet
    environment:
      PATHFINDER_ETHEREUM_API_URL: ws://execution.mainnet.staker.dappnode:8546
      PATHFINDER_NETWORK: mainnet
